name: Run test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Install Node.js (use the correct version based on your project requirements)
      - name: Install Node.js v14
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Step 3: Install npm dependencies
      - name: Install npm dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: npm run test
